### ISSUE TITLE
デベロッパーツールのコンソール警告について

### ISSUE THREAD

**Issue by Akira07** [Veriteworks/CookieFix#1]
Magento 2.2.8を利用しています。

こちらのパッチ適用前の段階で、Amazonログインボタンがあるページなどで、以下のようなコンソールに警告が出ておりました。
パッチ適用後も、同様にSameSiteの警告がコンソールに出たままなのですが、その状態で正常なのでしょうか？

また、Amazonログインや、Amazon Payでの購入は正常にできることを確認しております。

[![Screenshot from Gyazo](https://gyazo.com/94c22aa48347aec5a53e132d27c6b52c/raw)](https://gyazo.com/94c22aa48347aec5a53e132d27c6b52c)

**Comment by HirokazuNishi** [comment]
正常というか、ブラウザが出しているメッセージの内容をよく読んでいただければ理由がしっかり書いてあると思いますが・・・。

**Comment by Akira07** [comment]
返信ありがとうございます。

すみません、1点確認させてください。
コンソールの警告が表示されている状態は対応しないといけないもの、という認識だったのですが、そうではないということでしょうか？
（ブラウザが出しているメッセージのリンク先を読んだのですが、把握しきれず・・）

**Comment by HirokazuNishi** [comment]
それがどこのドメインの発行したCookieなのか、という話によると思います。
あなたが管理されているドメインが発行したものであるなら、調整するほうが良いでしょう。
ですが、あなたが管理していないドメインのCookieまで気にする必要があるでしょうか？
