### ISSUE TITLE
Incompatibility with  Magento 2.3.4

### ISSUE THREAD

**Issue by harshitshah20** [Veriteworks/CookieFix#10]
When trying to install module using composer on Magento 2.3.4, getting below error:

Problem 1
- Conclusion: remove magento/framework 102.0.4
- Conclusion: don't install magento/framework 102.0.4
- Installation request for veriteworks/cookiefix ^2.2 -> satisfiable by veriteworks/cookiefix[2.2.0].
- Conclusion: don't install magento/framework 102.0.4
- Conclusion: don't install magento/framework 102.0.4
- veriteworks/cookiefix 2.2.0 requires magento/framework ~102.0.5||~103.0.0 -> satisfiable by magento/framework[102.0.5-p2, 103.0.0, 102.0.5].
- Can only install one of: magento/framework[103.0.0, 102.0.4].
- Can only install one of: magento/framework[102.0.5-p2, 102.0.4].
- Can only install one of: magento/framework[102.0.5, 102.0.4].
- Can only install one of: magento/framework[102.0.4, 102.0.5-p2].
- Can only install one of: magento/framework[102.0.4, 103.0.0].
- Can only install one of: magento/framework[102.0.4, 102.0.5].
- Can only install one of: magento/framework[102.0.4, 102.0.5-p2].
- Can only install one of: magento/framework[102.0.4, 103.0.0].
- Can only install one of: magento/framework[102.0.4, 102.0.5].
- Installation request for magento/framework (locked at 102.0.4) -> satisfiable by magento/framework[102.0.4].

Probably this is because of the Magento framework version in Magento 2.3.4 is 102.0.4. Can you please advise and provide a workaround for installing on Magento 2.3.4?

**Comment by clivewalkden** [comment]
@harshitshah20 You may need to install the 1.0.6 version for 2.3.4 compatibility.

**Comment by HirokazuNishi** [comment]
Thanks @clivewalkden . @harshitshah20 , latest version is for Magento 2.3.5 and later. If you hope to use this against 2.3.4, please use 1.0.6. Magento did backward incompatibility changes on 2.3.5.

**Comment by HirokazuNishi** [comment]
@harshitshah20 I released new version 2.3.1. It can use for all 2.3.x (thanks @vovsky !).
