### ISSUE TITLE
[Feature Request] Add configuration for appling the Cookie Fix on specific Actions, Modules only

### ISSUE THREAD

**Issue by tuyennn** [Veriteworks/CookieFix#19]
Base on 3DS payments issue on new Chrome Browser could only be happened with specific payments modules and actions.
Is this possible to add the fix for specific actions, controllers.., etc.

Then it could not affect the others functions as well

**Comment by HirokazuNishi** [comment]
For example? Which payment service?

**Comment by tuyennn** [comment]
@HirokazuNishi not sure but for all 3ds payments, because this fix is necessary while redirecting from gateway to Magento. On this period the session of customer might be lost.

**Comment by tuyennn** [comment]
Close due cookie is None affected customer logging in, last implement with affected key probably could be extended to fix the problem
