### ISSUE TITLE
Google ReCaptcha cookie issues

### ISSUE THREAD

**Issue by devchris79** [Veriteworks/CookieFix#2]
Hi HirokazuNishi,

I have tried the module but I am still seeing cookie issues from the Google ReCaptcha functionality:

![image](https://user-images.githubusercontent.com/43850303/76073401-740b0f80-5f91-11ea-81e2-a840145382cf.png)

It seems to be a consent cookie issue:

![image](https://user-images.githubusercontent.com/43850303/76073762-0dd2bc80-5f92-11ea-9650-bd8b48527db5.png)

**Comment by HirokazuNishi** [comment]
@devchris79 as I explained to you, the cookie was sent from Google domain. We cannot change google's behavior from our side.

SameSite cookie attribute can be set by origin domain servers. Not from browser side or 3rd parties.
Therefore "mage-*" cookie values that are created by JavaScript can't set SameSite attribute.

**Comment by devchris79** [comment]
Thanks for the help.
