### ISSUE TITLE
Doesn't work with 2.4.0

### ISSUE THREAD

**Issue by amolagre** [Veriteworks/CookieFix#31]
Not able to install with composer on 2.4.0. Gives below error - 

Using version ^3.0 for veriteworks/cookiefix
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install veriteworks/cookiefix 3.0.1|remove magento/product-community-edition 2.4.0|install magento/framework 102.0.6-p1
    - Conclusion: don't install magento/framework 102.0.6-p1
    - Conclusion: don't install veriteworks/cookiefix 3.0.1|don't install magento/product-community-edition 2.4.0|install magento/framework 102.0.6-p1
    - Installation request for magento/product-community-edition 2.4.0 -> satisfiable by magento/product-community-edition[2.4.0].
    - Conclusion: don't install veriteworks/cookiefix 3.0.1|install magento/framework 102.0.6-p1
    - Conclusion: don't install veriteworks/cookiefix 3.0.0|remove magento/framework 103.0.0|install magento/framework 102.0.6-p1
    - Conclusion: don't install veriteworks/cookiefix 3.0.0|don't install magento/framework 103.0.0|install magento/framework 102.0.6-p1
    - Installation request for veriteworks/cookiefix ^3.0 -> satisfiable by veriteworks/cookiefix[3.0.0, 3.0.1].
    - veriteworks/cookiefix 3.0.0 requires magento/framework ~102.0.6-p1||~103.0.1 -> satisfiable by magento/framework[102.0.7, 103.0.2-p1, 103.0.2, 103.0.1-p1, 102.0.6-p1, 103.0.1].
    - Can only install one of: magento/framework[102.0.7, 103.0.0].
    - Can only install one of: magento/framework[103.0.2-p1, 103.0.0].
    - Can only install one of: magento/framework[103.0.2, 103.0.0].
    - Can only install one of: magento/framework[103.0.1-p1, 103.0.0].
    - Can only install one of: magento/framework[103.0.1, 103.0.0].
    - Installation request for magento/framework (locked at 103.0.0) -> satisfiable by magento/framework[103.0.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by HirokazuNishi** [comment]
@amolagre 

Please use CookieFix 2.4.2. Magento 2.4.0 doesn't have native same site cookie feature.

**Comment by amolagre** [comment]
Ok.. yup I saw that and upgraded to 2.4.2
